version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
        - .env

  redis:
      image: "redis:alpine"
      ports:
          - "6379:6379"
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 30s
        timeout: 10s
        retries: 3